name: sheaa_path_app
description: Path of the Imams - a cross-platform prayer timing and athkar companion.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Core Logic
  adhan: ^2.0.0
  intl: ^0.20.2
  url_launcher: ^6.1.11
  android_intent_plus: ^6.0.0
  path_provider: ^2.0.15
  google_fonts: ^6.1.0
  geolocator: ^13.0.0
  geocoding: ^4.0.0
  shared_preferences: ^2.3.0
  package_info_plus: ^8.3.1
  hijri: ^3.0.0
  provider: ^6.0.0
  vibration: ^3.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  table_calendar: ^3.0.9
  google_sign_in: ^6.2.2
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.3
  flutter_dnd:
    path: packages/flutter_dnd
  flutter_animate: ^4.5.0
  showcaseview: ^3.0.0
  audioplayers: ^5.2.1
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  flutter_timezone: ^5.0.1
  permission_handler: ^11.3.0
  flutter_svg: ^2.0.10
  flutter_compass: ^0.8.0
  stream_transform: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

  image: any
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/audio/

